[project]
name = "eduagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []


[tool.uv]
exclude-dependencies = ["onnxruntime"]

[[tool.uv.index]]
name = "tsinghua"
url = "https://mirrors.aliyun.com/pypi/simple/"
# default = true

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://mirrors.aliyun.com/pytorch-wheels/cu130/"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu130" }
torchvision = { index = "pytorch-cu130" }
